### ISSUE TITLE
Membuat halaman update profil pelamar kerja

### ISSUE THREAD

**Issue by RhikoBremana** [mhdanpi/Kelompok161-Karrir#3]
Sebagai pelamar kerja, saya ingin mengupdate informasi diri yang sudah dibuat pada saat registrasi di website KARRIR.COM sehingga menjadi up to date

**Comment by RhikoBremana** [comment]
https://www.google.com/imgres?imgurl=http%3A%2F%2Fjavawebmedia.com%2Fblog%2Fwp-content%2Fuploads%2F2020%2F02%2Fcapture_006_13022020_081748-1024x490.jpg&imgrefurl=https%3A%2F%2Fjavawebmedia.com%2Fblog%2Fdownload-source-code-website-company-profile-lengkap-dengan-codeigniter-3-1-0%2F&tbnid=LK2VQMWPakoXKM&vet=12ahUKEwjgr_LBsN72AhUAXGwGHU71ATgQMygCegUIARC_AQ..i&docid=o9HlORaZOglreM&w=1024&h=490&q=contoh%20halaman%20profil&ved=2ahUKEwjgr_LBsN72AhUAXGwGHU71ATgQMygCegUIARC_AQ

**Comment by RhikoBremana** [comment]
https://www.google.com/imgres?imgurl=http%3A%2F%2Fjavawebmedia.com%2Fblog%2Fwp-content%2Fuploads%2F2020%2F02%2Fcapture_006_13022020_081748-1024x490.jpg&imgrefurl=https%3A%2F%2Fjavawebmedia.com%2Fblog%2Fdownload-source-code-website-company-profile-lengkap-dengan-codeigniter-3-1-0%2F&tbnid=LK2VQMWPakoXKM&vet=12ahUKEwjgr_LBsN72AhUAXGwGHU71ATgQMygCegUIARC_AQ..i&docid=o9HlORaZOglreM&w=1024&h=490&q=contoh%20halaman%20profil&ved=2ahUKEwjgr_LBsN72AhUAXGwGHU71ATgQMygCegUIARC_AQ

**Comment by RhikoBremana** [comment]
![image](https://user-images.githubusercontent.com/92252286/159880278-22049482-a682-490c-a768-a5d2259df690.png)

**Comment by mhdanpi** [comment]
contoh mockup update profil
